name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ankit7847
          outputs: dist/snake.svg

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3   # ✅ FIXED (v3 latest for pages)

        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4   # ✅ latest
